### ISSUE TITLE
Set Application title and favicon

### ISSUE THREAD

**Issue by marcgauch** [marcgauch/dashboard-design#38]
Currently Vite App and the default Vue Favicon

**Comment by marcgauch** [comment]
icon: https://www.hoststar.ch/de/tools/favicon-generator
title: Folder Analyzer

**Comment by elly2178** [comment]
example icon Data report: https://www.flaticon.com/free-icon/data-report_10848640

**Comment by marcgauch** [comment]
Closed with https://github.com/marcgauch/dashboard-design/pull/44
